name: Ensaios do Paul Graham
description: Tradução dos ensaios do Paul Graham em português / Paul Graham's essays in Portuguese translation
authors:
  everton:
    name: Everton J. Carpes
    email: everton.carpes@gmail.com
    gravatar: evertoncarpes
    twitter: everton_carpes
    github: everton
  rsnows:
    name: Roberto Soares Neves
    email: rsnows@gmail.com
    twitter: rsnows
    github: rsnows
baseurl: /ensaios-paul-graham
url: http://everton.github.io/
exclude: [Gemfile, Gemfile.lock]
